project:
  type: website

website:
  title: "Text-as-Data Fall 2022"
  site-url: https://dacss.github.io/Text_as_Data_Fall_2022/
  twitter-card:
    creator: "@UMassDACSS"
    site: "@UMassDACSS"
  favicon: images/DACSS_Round_Network.png
  navbar:
    background: "#881c1c"
    logo: images/UMass White Wordmark Horiz.png
    right:
      - text: "Fall 2022"
        href: https://dacss.github.io/Text_as_Data_Fall_2022/
      - text: "Contributors"
        file: about.qmd
      - href: https://umass.edu/sbs/dacss
        text: "DACSS"
      - icon: github
        href: https://github.com/DACSS/Text_as_Data_Fall_2022
        aria-label: GitHub

execution:
  freeze: auto


format:
  html:
    mainfont: Open Sans
    linkcolor: "#881c1c"
    toc: true
    theme: 
      light: [flatly, styles.scss]
      dark: [darkly, styles.scss]
