{
  "hash": "6e7323864fe959a08e064dd65a20d676",
  "result": {
    "markdown": "---\ntitle: \"Blog Post 5\"\nauthor: \"Claire Battaglia\"\ndesription: \"Topic Models\"\ndate: \"11/13/2022\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - Claire Battaglia\n  - text-as-data\n  - blog post 5\n  - open-text survey response\n  - supervised learning\n  - topic models\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(readxl)\nlibrary(plyr)\nlibrary(tidyverse)\nlibrary(tidytext)\nlibrary(quanteda)\nlibrary(stm)\n\nknitr::opts_chunk$set(echo = TRUE)\n```\n:::\n\n\nIn my last post I applied dictionary methods to my corpus: responses to the open-text survey question \"What changes would you like to see for Missoula’s food system?\" I used both the NRC and General Inquirer dictionaries to conduct a sentiment analysis but ultimately decided that this was not an appropriate analysis for my corpus. This is primarily because the survey question doesn't ask specifically about respondents' feelings about anything, meaning that a typical valid response doesn't contain either positive or negative sentiment.\n\nI plan to create my own dictionary at some point but for this post I will be attempting to analyze my corpus using Structural Topic Modeling (STM). This method of analysis will allow me to understand both the prevalence of topics across my corpus and the content (i.e. words used to talk about) those topics. Importantly, STM will allow me to analyze the responses alongside some covariates of interest. The two that I am particularly interested in are ZIP Code and annual household income. I expect that at least the *prevalence* of topics will vary by these two covariates, if not the *content*. Keeping the long term goal of this analysis in mind, it makes a tremendous difference if respondents recommending a particular change to the food system are concentrated in a single ZIP Code or income bracket or distributed across the city/over all income brackets.\n\n## Creating My Document Feature Matrix\n\nI created a DFM in a previous post but I'll create a new one here because the one I previously created doesn't contain the covariates I'm interested in.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load tidy data\nload(\"CFA_tidy.RData\")\n\n# create dfm\ndfm_change <- dfm(tokens(CFA_tidy$change),\n             tolower = TRUE,\n             remove = stopwords(\"en\"),\n             remove_punct = TRUE)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: '...' should not be used for tokens() arguments; use 'tokens()' first.\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: 'remove' is deprecated; use dfm_remove() instead\n```\n:::\n\n```{.r .cell-code}\n# get dimensions\ndim(dfm_change)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1]  215 1146\n```\n:::\n:::\n\n\nIt contains 215 rows (the responses, called documents here) and 1,146 columns (all the words that appear in the corpus).\n\n<aside> When I first attempted to build a STM, I noticed that the `stm()` function automatically removed *NA* values but that that created problems in later functions. I went back to my tidy dataset and removed all rows that contained any *NA* values to try and address that. Of the 389 respondents, only 215 answered every question. </aside>\n\nNow I'll take a quick look at the two covariates I am interested in: ZIP Code and annual household income.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# zip\ntable(CFA_tidy$zip)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n59701 59801 59802 59803 59804 59808 59821 59823 59825 59826 59833 59846 59847 \n    1    85    62    20     9    15     1     5     4     1     2     1     5 \n59860 59864 59868 59908 \n    1     1     1     1 \n```\n:::\n\n```{.r .cell-code}\n# income\ntable(CFA_tidy$income)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nBetween $100,000 and $249,999   Between $25,000 and $34,999 \n                           55                            21 \n  Between $35,000 and $49,999   Between $50,000 and $99,999 \n                           37                            66 \n                Over $250,000                 Under $25,000 \n                            8                            28 \n```\n:::\n:::\n\n\n## Correlated Topic Model\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# build correlated topic model\nctm_change <- stm(dfm_change, K = 5,\n                       verbose = FALSE, init.type = \"Spectral\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in dfm2stm(x, docvars, omit_empty = TRUE): Dropped empty document(s):\ntext96\n```\n:::\n\n```{.r .cell-code}\n# get summary\nsummary(ctm_change)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nA topic model with 5 topics, 214 documents and a 1146 word dictionary.\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nTopic 1 Top Words:\n \t Highest Prob: food, land, healthy, affordable, education, farm, agricultural \n \t FREX: healthy, change, opportunities, education, many, less, use \n \t Lift: healthy, 1, 10, advocacy, alleviate, along, among \n \t Score: healthy, agricultural, among, evidence-based, might, resource, use \nTopic 2 Top Words:\n \t Highest Prob: food, gardens, year, missoula, community, bank, need \n \t FREX: year, round, county, bank, need, gardens, high \n \t Lift: #11, 2-5x, ability, adapted, allowing, always, appealing \n \t Score: year, feeding, bank, boulevards, progress, double, cans \nTopic 3 Top Words:\n \t Highest Prob: local, food, like, see, farmers, good, organic \n \t FREX: organic, preserve, prices, nutrition, section, good, easier \n \t Lift: -or, $, 5-, abundant, actually, additional, address \n \t Score: good, section, poor, organic, crop, fewer, lose \nTopic 4 Top Words:\n \t Highest Prob: affordable, options, grown, local, locally, grocery, stores \n \t FREX: grown, farming, neighborhoods, home, gardening, dairy, raised \n \t Lift: accessed, acquisition, activities, adaptation, affordablity, allowed, apartments \n \t Score: csa, neighborhoods, farming, livestock, shares, gardening, example \nTopic 5 Top Words:\n \t Highest Prob: local, food, sustainable, locally, foods, produce, school \n \t FREX: greater, afford, sourced, sustainable, school, local, buying \n \t Lift: sourced, +, 1,000, adults, alone, amazing, amounts \n \t Score: composting, sourced, buying, missoulians, extra, care, fresh \n```\n:::\n:::\n\n\nA few things to note:\n\n* It looks like the `stm()` function automatically drops empty documents. Because I removed all rows that contained *NA* values from my tidy dataset, however, I am not sure why Text 96 is being considered \"empty.\" I have a feeling this is going to cause problems later on.\n* I specified that *k* = 5 and while that doesn't seem unreasonable, I did just make that number up.\n* There are packages and functions specifically for building CTM but here I used the `stm()` function from the `stm` package because I am ultimately building a STM and not a CTM.\n\nNext I'll use the `labelTopics()` function to take a look at the words that are associated with each of the five topics that have been revealed.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# label topics\nlabelTopics(ctm_change)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nTopic 1 Top Words:\n \t Highest Prob: food, land, healthy, affordable, education, farm, agricultural \n \t FREX: healthy, change, opportunities, education, many, less, use \n \t Lift: healthy, 1, 10, advocacy, alleviate, along, among \n \t Score: healthy, agricultural, among, evidence-based, might, resource, use \nTopic 2 Top Words:\n \t Highest Prob: food, gardens, year, missoula, community, bank, need \n \t FREX: year, round, county, bank, need, gardens, high \n \t Lift: #11, 2-5x, ability, adapted, allowing, always, appealing \n \t Score: year, feeding, bank, boulevards, progress, double, cans \nTopic 3 Top Words:\n \t Highest Prob: local, food, like, see, farmers, good, organic \n \t FREX: organic, preserve, prices, nutrition, section, good, easier \n \t Lift: -or, $, 5-, abundant, actually, additional, address \n \t Score: good, section, poor, organic, crop, fewer, lose \nTopic 4 Top Words:\n \t Highest Prob: affordable, options, grown, local, locally, grocery, stores \n \t FREX: grown, farming, neighborhoods, home, gardening, dairy, raised \n \t Lift: accessed, acquisition, activities, adaptation, affordablity, allowed, apartments \n \t Score: csa, neighborhoods, farming, livestock, shares, gardening, example \nTopic 5 Top Words:\n \t Highest Prob: local, food, sustainable, locally, foods, produce, school \n \t FREX: greater, afford, sourced, sustainable, school, local, buying \n \t Lift: sourced, +, 1,000, adults, alone, amazing, amounts \n \t Score: composting, sourced, buying, missoulians, extra, care, fresh \n```\n:::\n:::\n\n\nAccording to the [package documentation](https://cran.r-project.org/web/packages/stm/vignettes/stmVignette.pdf):\n\n**Highest Probability** are the words with the highest probability of association with that topic .\n\n**FREX** weights words by their overall frequency and how exclusive they are to that topic.\n\n**Lift** weights words by dividing by their frequency in other topics.\n\n**Score** divides the log frequency of the word in the topic by the log frequency of the word in other topics.\n\nNext the `findThoughts()` function will allow me to see an example document that is highly associated with each of the five topics.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# find thoughts\nfindThoughts(ctm_change,\n             texts = CFA_tidy$change,\n             topics = c(1:5),\n             n = 1)\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in findThoughts(ctm_change, texts = CFA_tidy$change, topics = c(1:5), : Number of provided texts and number of documents modeled do not match\n```\n:::\n:::\n\n\nI think that this error is occurring because Text 96 was removed and so now there are 215 rows in my dataset but only 214 texts. As mentioned previously, I am not sure why Text 96 was removed so I'll take a look at it now and see if I can figure it out.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# get text 96\nCFA_tidy[96,]\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 5\n  id          zip     age income                      change\n  <chr>       <chr> <dbl> <chr>                       <chr> \n1 12981031063 59802    63 Between $50,000 and $99,999 ?     \n```\n:::\n:::\n\nI see the problem. That row was not removed when I removed rows with *NA* values but the *change* cell contains no information in my DFM because I removed punctuation. I'll remove that row and see if that fixes the problem.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# remove row 96\nCFA_tidy_2 <- subset(CFA_tidy, change !=\"?\")\n\n# save\nsave(CFA_tidy_2, file = \"CFA_tidy_2.RData\")\n\n# view to check\nprint(CFA_tidy_2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 214 × 5\n   id          zip     age income                        change                 \n   <chr>       <chr> <dbl> <chr>                         <chr>                  \n 1 12978141302 59823    72 Under $25,000                 \"More concentration on…\n 2 12991074702 59802    29 Between $50,000 and $99,999   \"I'd like to see more …\n 3 12985165265 59801    60 Between $50,000 and $99,999   \"Factual, evidence-bas…\n 4 12978197761 59801    61 Between $50,000 and $99,999   \"Whatever it takes to …\n 5 13020467460 59801    83 Between $35,000 and $49,999   \"More competitive pric…\n 6 12972697121 59802    56 Between $100,000 and $249,999 \"More education about …\n 7 12977827881 59803    65 Between $50,000 and $99,999   \"Greater focus on loca…\n 8 13003104091 59808    29 Between $35,000 and $49,999   \"I applaud good food s…\n 9 12981080680 59801    54 Between $100,000 and $249,999 \"More policies and pro…\n10 12977865121 59802    27 Under $25,000                 \"An expansion of more …\n# … with 204 more rows\n```\n:::\n:::\n\n\nEverything looks good to me so now I'll create a new DFM from my new tidy dataset.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# create dfm\ndfm_change_2 <- dfm(tokens(CFA_tidy_2$change),\n             tolower = TRUE,\n             remove = stopwords(\"en\"),\n             remove_punct = TRUE)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: '...' should not be used for tokens() arguments; use 'tokens()' first.\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: 'remove' is deprecated; use dfm_remove() instead\n```\n:::\n\n```{.r .cell-code}\n# save\nsave(dfm_change_2, file = \"dfm_change_2.RData\")\n\n# get dimensions\ndim(dfm_change_2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1]  214 1146\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# build correlated topic model\nctm_change_2 <- stm(dfm_change_2, K = 5,\n                       verbose = FALSE, init.type = \"Spectral\")\n# get summary\nsummary(ctm_change_2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nA topic model with 5 topics, 214 documents and a 1146 word dictionary.\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nTopic 1 Top Words:\n \t Highest Prob: food, land, healthy, affordable, education, farm, agricultural \n \t FREX: healthy, change, opportunities, education, many, less, use \n \t Lift: healthy, 1, 10, advocacy, alleviate, along, among \n \t Score: healthy, agricultural, among, evidence-based, might, resource, use \nTopic 2 Top Words:\n \t Highest Prob: food, gardens, year, missoula, community, bank, need \n \t FREX: year, round, county, bank, need, gardens, high \n \t Lift: #11, 2-5x, ability, adapted, allowing, always, appealing \n \t Score: year, feeding, bank, boulevards, progress, double, cans \nTopic 3 Top Words:\n \t Highest Prob: local, food, like, see, farmers, good, organic \n \t FREX: organic, preserve, prices, nutrition, section, good, easier \n \t Lift: -or, $, 5-, abundant, actually, additional, address \n \t Score: good, section, poor, organic, crop, fewer, lose \nTopic 4 Top Words:\n \t Highest Prob: affordable, options, grown, local, locally, grocery, stores \n \t FREX: grown, farming, neighborhoods, home, gardening, dairy, raised \n \t Lift: accessed, acquisition, activities, adaptation, affordablity, allowed, apartments \n \t Score: csa, neighborhoods, farming, livestock, shares, gardening, example \nTopic 5 Top Words:\n \t Highest Prob: local, food, sustainable, locally, foods, produce, school \n \t FREX: greater, afford, sourced, sustainable, school, local, buying \n \t Lift: sourced, +, 1,000, adults, alone, amazing, amounts \n \t Score: composting, sourced, buying, missoulians, extra, care, fresh \n```\n:::\n\n```{.r .cell-code}\n# label topics\nlabelTopics(ctm_change_2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nTopic 1 Top Words:\n \t Highest Prob: food, land, healthy, affordable, education, farm, agricultural \n \t FREX: healthy, change, opportunities, education, many, less, use \n \t Lift: healthy, 1, 10, advocacy, alleviate, along, among \n \t Score: healthy, agricultural, among, evidence-based, might, resource, use \nTopic 2 Top Words:\n \t Highest Prob: food, gardens, year, missoula, community, bank, need \n \t FREX: year, round, county, bank, need, gardens, high \n \t Lift: #11, 2-5x, ability, adapted, allowing, always, appealing \n \t Score: year, feeding, bank, boulevards, progress, double, cans \nTopic 3 Top Words:\n \t Highest Prob: local, food, like, see, farmers, good, organic \n \t FREX: organic, preserve, prices, nutrition, section, good, easier \n \t Lift: -or, $, 5-, abundant, actually, additional, address \n \t Score: good, section, poor, organic, crop, fewer, lose \nTopic 4 Top Words:\n \t Highest Prob: affordable, options, grown, local, locally, grocery, stores \n \t FREX: grown, farming, neighborhoods, home, gardening, dairy, raised \n \t Lift: accessed, acquisition, activities, adaptation, affordablity, allowed, apartments \n \t Score: csa, neighborhoods, farming, livestock, shares, gardening, example \nTopic 5 Top Words:\n \t Highest Prob: local, food, sustainable, locally, foods, produce, school \n \t FREX: greater, afford, sourced, sustainable, school, local, buying \n \t Lift: sourced, +, 1,000, adults, alone, amazing, amounts \n \t Score: composting, sourced, buying, missoulians, extra, care, fresh \n```\n:::\n\n```{.r .cell-code}\n# find thoughts\nfindThoughts(ctm_change_2,\n             texts = CFA_tidy_2$change,\n             topics = c(1:5),\n             n = 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n Topic 1: \n \t I would like to see more preservation of agricultural land (particularly in the Target Range/Mullen area), as opposed to subdividing it and building houses. I realize there's a shortage of affordable housing, but if we build over the land, we will never get it back, or if we do, it will take years to rebuild the soil structure and health. I would also like to see less city space paved over with asphalt/concrete, and instead dedicated to community gardens, green space, shade trees, and food forests. With a stronger community focus on maintaining these spaces—along with community education and investment to discourage vandalism!—I believe we could make food more available to everyone during the growing months to help alleviate food hunger, put our drop in the bucket to slow climate change, and beautify the city at the same time. It requires an immense cultural shift and education, unfortunately, but it could be a tremendous thing. \n Topic 2: \n \t Love to see the City of Missoula promote edible and/or native plantings in boulevards, parks etc.  No reason why our city boulevards could not support significant food production of fruit and nut producing plants. \n Topic 3: \n \t No more chain grocery stores. Lower cost nutritious food opportunities- Good Food has great options but it’s not accessible for the typical resident. I would like to see fewer Albertsons, Fresh Markets -OR if we must have large chains, could we require that they either support local farms or give a portion of proceeds to local farms so they can build their infrastructure up, then be able to be a more reliable producer for our local grocery stores, regardless whether they are chain or local.     Truly, I would love a cheaper good food store. My husband and I jointly make a good living and it’s tough to actually shop there. It’s just not accessible for folks, but I want to support as much local produce as possible outside of what I buy at farmers market.     What if our farmers market had a good section and a products/non food section? That could make it easier to pop in and out for busy lives. \n Topic 4: \n \t The urban sprawl and development of prime farm land is a big deal. Once a subdivision is built, there is no going back.  It would also be nice if urban farms could legally raise livestock including more than 6 chickens, pigs, cows and goats. Urban farms would be more effficient systems if they were allowed to integrate livestock into their farming systems. For example, grazing animals to keep grass and weeds down, pigs to feed farm/food waste too, and all of the manure to compost and use for fertilizer. \n Topic 5: \n \t An expansion of more produce for low income families in aid packages. The boost in farmer’s market coupons and extra produce with wic during summer is amazing but in the winter it’s just back to way too much cereal and grains which isn’t okay. One of our biggest issues in the winter is finding funds for a variety of fresh foods since everything becomes so much more expensive. I’m not vying for pineapples in January or anything but maybe an indoor farmer’s market to get greens and greenhouse crops from local farmers. That could extend the farmer’s season and provide more fresh options to missoulians that haven’t traveled 1,000+ miles\n```\n:::\n:::\n\n\nYes! That seems to have resolved the problem. Now I'll use the second DFM to build a STM.\n\n## Structured Topic Model\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# specify number of topics\nk <- 5\n\n# specify model\nstm_change <- stm(dfm_change_2,\n               K = k,\n               prevalence = ~ zip,\n               data = CFA_tidy_2,\n               max.em.its = 1000,\n               seed = 1234,\n               init.type = \"Spectral\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nBeginning Spectral Initialization \n\t Calculating the gram matrix...\n\t Finding anchor words...\n \t.....\n\t Recovering initialization...\n \t...........\nInitialization complete.\n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 1 (approx. per word bound = -6.423) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 2 (approx. per word bound = -6.269, relative change = 2.408e-02) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 3 (approx. per word bound = -6.219, relative change = 7.884e-03) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 4 (approx. per word bound = -6.200, relative change = 3.061e-03) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 5 (approx. per word bound = -6.192, relative change = 1.414e-03) \nTopic 1: land, farmers, affordable, locally, missoula \n Topic 2: options, can, school, use, need \n Topic 3: local, like, support, access, healthy \n Topic 4: community, see, foods, sustainable, stores \n Topic 5: food, farm, education, grocery, markets \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 6 (approx. per word bound = -6.187, relative change = 7.739e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 7 (approx. per word bound = -6.184, relative change = 4.977e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 8 (approx. per word bound = -6.181, relative change = 3.732e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 9 (approx. per word bound = -6.179, relative change = 3.183e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 10 (approx. per word bound = -6.178, relative change = 2.969e-04) \nTopic 1: land, farmers, affordable, locally, missoula \n Topic 2: options, can, school, use, need \n Topic 3: local, like, support, access, healthy \n Topic 4: community, foods, sustainable, see, stores \n Topic 5: food, farm, education, grocery, markets \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 11 (approx. per word bound = -6.176, relative change = 2.932e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 12 (approx. per word bound = -6.174, relative change = 2.974e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 13 (approx. per word bound = -6.172, relative change = 2.976e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 14 (approx. per word bound = -6.170, relative change = 2.866e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 15 (approx. per word bound = -6.169, relative change = 2.790e-04) \nTopic 1: land, farmers, affordable, locally, missoula \n Topic 2: options, can, school, gardens, use \n Topic 3: local, like, see, support, access \n Topic 4: community, foods, sustainable, stores, see \n Topic 5: food, farm, education, grocery, markets \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 16 (approx. per word bound = -6.167, relative change = 2.833e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 17 (approx. per word bound = -6.165, relative change = 2.796e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 18 (approx. per word bound = -6.164, relative change = 2.521e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 19 (approx. per word bound = -6.162, relative change = 2.245e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 20 (approx. per word bound = -6.161, relative change = 2.306e-04) \nTopic 1: land, farmers, affordable, locally, missoula \n Topic 2: options, gardens, can, school, use \n Topic 3: local, like, see, access, support \n Topic 4: community, foods, sustainable, stores, available \n Topic 5: food, farm, education, grocery, markets \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 21 (approx. per word bound = -6.159, relative change = 2.807e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 22 (approx. per word bound = -6.157, relative change = 2.981e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 23 (approx. per word bound = -6.155, relative change = 2.962e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 24 (approx. per word bound = -6.154, relative change = 2.918e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 25 (approx. per word bound = -6.152, relative change = 3.095e-04) \nTopic 1: land, farmers, affordable, locally, missoula \n Topic 2: options, gardens, can, school, less \n Topic 3: local, like, see, access, support \n Topic 4: community, foods, sustainable, stores, available \n Topic 5: food, farm, education, markets, grocery \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 26 (approx. per word bound = -6.149, relative change = 3.628e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 27 (approx. per word bound = -6.147, relative change = 4.229e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 28 (approx. per word bound = -6.144, relative change = 4.438e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 29 (approx. per word bound = -6.141, relative change = 4.420e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 30 (approx. per word bound = -6.139, relative change = 4.279e-04) \nTopic 1: land, farmers, affordable, locally, missoula \n Topic 2: options, gardens, can, school, less \n Topic 3: local, like, see, access, support \n Topic 4: community, foods, sustainable, stores, available \n Topic 5: food, farm, education, markets, produce \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 31 (approx. per word bound = -6.136, relative change = 3.915e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 32 (approx. per word bound = -6.134, relative change = 3.691e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 33 (approx. per word bound = -6.132, relative change = 3.782e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 34 (approx. per word bound = -6.129, relative change = 4.312e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 35 (approx. per word bound = -6.126, relative change = 5.276e-04) \nTopic 1: land, farmers, affordable, locally, missoula \n Topic 2: options, gardens, can, school, less \n Topic 3: local, like, see, access, support \n Topic 4: community, foods, sustainable, stores, available \n Topic 5: food, farm, education, produce, markets \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 36 (approx. per word bound = -6.123, relative change = 5.508e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 37 (approx. per word bound = -6.120, relative change = 4.525e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 38 (approx. per word bound = -6.118, relative change = 3.735e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 39 (approx. per word bound = -6.115, relative change = 3.611e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 40 (approx. per word bound = -6.113, relative change = 3.875e-04) \nTopic 1: land, farmers, affordable, locally, missoula \n Topic 2: options, gardens, can, school, less \n Topic 3: local, like, see, access, support \n Topic 4: community, foods, sustainable, stores, available \n Topic 5: food, farm, education, produce, markets \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 41 (approx. per word bound = -6.111, relative change = 3.918e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 42 (approx. per word bound = -6.108, relative change = 3.538e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 43 (approx. per word bound = -6.106, relative change = 3.188e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 44 (approx. per word bound = -6.105, relative change = 2.924e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 45 (approx. per word bound = -6.103, relative change = 2.686e-04) \nTopic 1: land, farmers, affordable, locally, missoula \n Topic 2: options, gardens, can, school, less \n Topic 3: local, like, see, access, support \n Topic 4: community, sustainable, foods, stores, available \n Topic 5: food, farm, education, produce, markets \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 46 (approx. per word bound = -6.101, relative change = 2.552e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 47 (approx. per word bound = -6.100, relative change = 2.613e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 48 (approx. per word bound = -6.098, relative change = 2.714e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 49 (approx. per word bound = -6.097, relative change = 2.625e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 50 (approx. per word bound = -6.095, relative change = 2.481e-04) \nTopic 1: farmers, land, affordable, locally, missoula \n Topic 2: options, gardens, can, school, use \n Topic 3: local, like, see, access, support \n Topic 4: community, sustainable, stores, available, grown \n Topic 5: food, farm, education, produce, markets \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 51 (approx. per word bound = -6.094, relative change = 2.293e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 52 (approx. per word bound = -6.092, relative change = 2.188e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 53 (approx. per word bound = -6.091, relative change = 2.458e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 54 (approx. per word bound = -6.089, relative change = 3.238e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 55 (approx. per word bound = -6.086, relative change = 4.410e-04) \nTopic 1: farmers, land, affordable, locally, missoula \n Topic 2: options, gardens, can, school, use \n Topic 3: local, like, see, access, healthy \n Topic 4: community, sustainable, stores, available, grown \n Topic 5: food, farm, education, produce, markets \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 56 (approx. per word bound = -6.083, relative change = 5.361e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 57 (approx. per word bound = -6.080, relative change = 5.539e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 58 (approx. per word bound = -6.077, relative change = 5.040e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 59 (approx. per word bound = -6.074, relative change = 4.375e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 60 (approx. per word bound = -6.071, relative change = 3.993e-04) \nTopic 1: farmers, land, affordable, locally, missoula \n Topic 2: options, gardens, can, school, use \n Topic 3: local, like, see, access, healthy \n Topic 4: community, sustainable, stores, available, grown \n Topic 5: food, farm, foods, education, produce \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 61 (approx. per word bound = -6.069, relative change = 4.126e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 62 (approx. per word bound = -6.066, relative change = 4.827e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 63 (approx. per word bound = -6.063, relative change = 5.401e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 64 (approx. per word bound = -6.059, relative change = 5.677e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 65 (approx. per word bound = -6.056, relative change = 5.988e-04) \nTopic 1: farmers, land, affordable, locally, missoula \n Topic 2: options, gardens, can, school, use \n Topic 3: local, like, see, access, healthy \n Topic 4: community, sustainable, stores, available, grown \n Topic 5: food, foods, farm, education, produce \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 66 (approx. per word bound = -6.052, relative change = 5.196e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 67 (approx. per word bound = -6.050, relative change = 4.743e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 68 (approx. per word bound = -6.047, relative change = 4.946e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 69 (approx. per word bound = -6.044, relative change = 5.082e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 70 (approx. per word bound = -6.041, relative change = 5.014e-04) \nTopic 1: farmers, land, affordable, locally, agricultural \n Topic 2: gardens, options, school, can, use \n Topic 3: local, like, see, access, healthy \n Topic 4: community, sustainable, stores, available, grown \n Topic 5: food, local, foods, farm, education \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 71 (approx. per word bound = -6.037, relative change = 5.035e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 72 (approx. per word bound = -6.034, relative change = 4.998e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 73 (approx. per word bound = -6.032, relative change = 4.876e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 74 (approx. per word bound = -6.029, relative change = 4.855e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 75 (approx. per word bound = -6.026, relative change = 4.937e-04) \nTopic 1: farmers, land, affordable, locally, agricultural \n Topic 2: gardens, school, can, use, people \n Topic 3: local, like, see, access, healthy \n Topic 4: community, sustainable, stores, options, available \n Topic 5: food, local, foods, education, farm \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 76 (approx. per word bound = -6.023, relative change = 4.669e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 77 (approx. per word bound = -6.020, relative change = 4.229e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 78 (approx. per word bound = -6.018, relative change = 4.153e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 79 (approx. per word bound = -6.015, relative change = 4.167e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 80 (approx. per word bound = -6.013, relative change = 4.059e-04) \nTopic 1: farmers, land, affordable, locally, agricultural \n Topic 2: gardens, school, can, people, use \n Topic 3: like, local, see, access, healthy \n Topic 4: community, sustainable, options, stores, available \n Topic 5: food, local, foods, education, support \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 81 (approx. per word bound = -6.010, relative change = 4.200e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 82 (approx. per word bound = -6.007, relative change = 4.760e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 83 (approx. per word bound = -6.004, relative change = 5.490e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 84 (approx. per word bound = -6.001, relative change = 5.047e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 85 (approx. per word bound = -5.998, relative change = 4.375e-04) \nTopic 1: farmers, land, affordable, locally, agricultural \n Topic 2: gardens, school, can, people, garden \n Topic 3: like, see, local, access, healthy \n Topic 4: community, options, sustainable, stores, farm \n Topic 5: food, local, foods, support, produce \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 86 (approx. per word bound = -5.996, relative change = 4.742e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 87 (approx. per word bound = -5.992, relative change = 5.505e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 88 (approx. per word bound = -5.989, relative change = 5.307e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 89 (approx. per word bound = -5.986, relative change = 4.499e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 90 (approx. per word bound = -5.984, relative change = 4.113e-04) \nTopic 1: farmers, affordable, land, locally, agricultural \n Topic 2: gardens, school, can, garden, restaurants \n Topic 3: like, see, access, local, healthy \n Topic 4: community, options, sustainable, farm, stores \n Topic 5: food, local, foods, support, produce \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 91 (approx. per word bound = -5.982, relative change = 3.500e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 92 (approx. per word bound = -5.980, relative change = 2.971e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 93 (approx. per word bound = -5.978, relative change = 2.745e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 94 (approx. per word bound = -5.977, relative change = 2.884e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 95 (approx. per word bound = -5.975, relative change = 3.462e-04) \nTopic 1: farmers, affordable, land, locally, agricultural \n Topic 2: gardens, school, can, garden, restaurants \n Topic 3: like, see, access, healthy, local \n Topic 4: community, options, farm, sustainable, stores \n Topic 5: food, local, foods, support, produce \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 96 (approx. per word bound = -5.972, relative change = 3.726e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 97 (approx. per word bound = -5.970, relative change = 3.430e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 98 (approx. per word bound = -5.968, relative change = 3.284e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 99 (approx. per word bound = -5.966, relative change = 3.603e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 100 (approx. per word bound = -5.964, relative change = 4.259e-04) \nTopic 1: farmers, affordable, land, locally, agricultural \n Topic 2: gardens, school, can, restaurants, bank \n Topic 3: like, see, access, local, good \n Topic 4: community, options, farm, sustainable, stores \n Topic 5: food, local, foods, support, produce \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 101 (approx. per word bound = -5.962, relative change = 3.679e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 102 (approx. per word bound = -5.960, relative change = 2.857e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 103 (approx. per word bound = -5.958, relative change = 2.752e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 104 (approx. per word bound = -5.956, relative change = 3.026e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 105 (approx. per word bound = -5.955, relative change = 3.128e-04) \nTopic 1: farmers, affordable, land, locally, healthy \n Topic 2: gardens, school, can, restaurants, bank \n Topic 3: like, see, access, local, good \n Topic 4: community, farm, options, sustainable, stores \n Topic 5: food, local, foods, support, produce \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 106 (approx. per word bound = -5.953, relative change = 3.053e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 107 (approx. per word bound = -5.951, relative change = 3.274e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 108 (approx. per word bound = -5.949, relative change = 3.594e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 109 (approx. per word bound = -5.946, relative change = 3.892e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 110 (approx. per word bound = -5.944, relative change = 3.944e-04) \nTopic 1: farmers, affordable, locally, land, healthy \n Topic 2: gardens, school, restaurants, bank, markets \n Topic 3: like, see, access, local, good \n Topic 4: community, farm, sustainable, options, stores \n Topic 5: food, local, foods, support, produce \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 111 (approx. per word bound = -5.942, relative change = 3.899e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 112 (approx. per word bound = -5.939, relative change = 3.774e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 113 (approx. per word bound = -5.937, relative change = 3.590e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 114 (approx. per word bound = -5.935, relative change = 3.330e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 115 (approx. per word bound = -5.933, relative change = 3.194e-04) \nTopic 1: farmers, affordable, locally, land, healthy \n Topic 2: gardens, school, restaurants, bank, markets \n Topic 3: like, see, access, local, good \n Topic 4: community, farm, sustainable, options, stores \n Topic 5: food, local, foods, support, produce \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 116 (approx. per word bound = -5.931, relative change = 3.246e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 117 (approx. per word bound = -5.930, relative change = 3.133e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 118 (approx. per word bound = -5.928, relative change = 2.583e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 119 (approx. per word bound = -5.927, relative change = 2.192e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 120 (approx. per word bound = -5.925, relative change = 2.233e-04) \nTopic 1: farmers, affordable, locally, land, healthy \n Topic 2: gardens, school, restaurants, bank, markets \n Topic 3: like, see, access, local, good \n Topic 4: community, farm, sustainable, options, stores \n Topic 5: food, local, foods, support, produce \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 121 (approx. per word bound = -5.924, relative change = 2.418e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 122 (approx. per word bound = -5.922, relative change = 2.756e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 123 (approx. per word bound = -5.921, relative change = 3.181e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 124 (approx. per word bound = -5.918, relative change = 3.678e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 125 (approx. per word bound = -5.916, relative change = 3.447e-04) \nTopic 1: affordable, farmers, locally, land, healthy \n Topic 2: gardens, restaurants, bank, markets, school \n Topic 3: like, see, access, local, good \n Topic 4: community, farm, sustainable, options, stores \n Topic 5: food, local, foods, support, produce \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 126 (approx. per word bound = -5.914, relative change = 3.374e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 127 (approx. per word bound = -5.912, relative change = 3.629e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 128 (approx. per word bound = -5.910, relative change = 3.782e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 129 (approx. per word bound = -5.908, relative change = 3.799e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 130 (approx. per word bound = -5.905, relative change = 3.810e-04) \nTopic 1: affordable, land, locally, farmers, healthy \n Topic 2: gardens, restaurants, bank, year, markets \n Topic 3: like, see, local, access, good \n Topic 4: community, farm, sustainable, options, stores \n Topic 5: food, local, foods, support, produce \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 131 (approx. per word bound = -5.903, relative change = 3.800e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 132 (approx. per word bound = -5.901, relative change = 4.022e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 133 (approx. per word bound = -5.899, relative change = 3.844e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 134 (approx. per word bound = -5.897, relative change = 3.289e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 135 (approx. per word bound = -5.895, relative change = 2.893e-04) \nTopic 1: affordable, land, locally, healthy, farmers \n Topic 2: gardens, restaurants, bank, year, markets \n Topic 3: like, see, local, access, school \n Topic 4: farm, sustainable, options, community, available \n Topic 5: food, local, foods, support, produce \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 136 (approx. per word bound = -5.893, relative change = 2.679e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 137 (approx. per word bound = -5.892, relative change = 2.895e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 138 (approx. per word bound = -5.890, relative change = 3.572e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 139 (approx. per word bound = -5.888, relative change = 3.201e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 140 (approx. per word bound = -5.886, relative change = 2.385e-04) \nTopic 1: affordable, land, locally, healthy, farmers \n Topic 2: gardens, restaurants, bank, year, missoula \n Topic 3: like, see, local, food, school \n Topic 4: farm, sustainable, options, community, available \n Topic 5: food, local, foods, support, produce \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 141 (approx. per word bound = -5.885, relative change = 2.432e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 142 (approx. per word bound = -5.883, relative change = 2.647e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 143 (approx. per word bound = -5.882, relative change = 2.854e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 144 (approx. per word bound = -5.880, relative change = 3.027e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 145 (approx. per word bound = -5.878, relative change = 3.256e-04) \nTopic 1: affordable, land, locally, healthy, agricultural \n Topic 2: gardens, restaurants, bank, year, missoula \n Topic 3: like, see, local, food, school \n Topic 4: farm, sustainable, options, available, grown \n Topic 5: food, local, foods, support, produce \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 146 (approx. per word bound = -5.876, relative change = 3.354e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 147 (approx. per word bound = -5.874, relative change = 3.350e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 148 (approx. per word bound = -5.872, relative change = 3.201e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 149 (approx. per word bound = -5.870, relative change = 2.646e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 150 (approx. per word bound = -5.869, relative change = 2.142e-04) \nTopic 1: affordable, locally, land, healthy, agricultural \n Topic 2: gardens, restaurants, year, bank, missoula \n Topic 3: like, see, local, food, school \n Topic 4: sustainable, options, farm, available, grown \n Topic 5: food, local, foods, support, produce \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 151 (approx. per word bound = -5.868, relative change = 1.815e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 152 (approx. per word bound = -5.867, relative change = 1.504e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 153 (approx. per word bound = -5.867, relative change = 1.244e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 154 (approx. per word bound = -5.866, relative change = 1.098e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 155 (approx. per word bound = -5.865, relative change = 9.780e-05) \nTopic 1: affordable, land, locally, healthy, agricultural \n Topic 2: gardens, restaurants, year, bank, missoula \n Topic 3: like, see, local, food, school \n Topic 4: options, sustainable, available, grown, meat \n Topic 5: food, local, foods, support, produce \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 156 (approx. per word bound = -5.865, relative change = 9.407e-05) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 157 (approx. per word bound = -5.864, relative change = 1.107e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 158 (approx. per word bound = -5.863, relative change = 1.594e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 159 (approx. per word bound = -5.862, relative change = 2.375e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 160 (approx. per word bound = -5.860, relative change = 2.918e-04) \nTopic 1: affordable, land, locally, healthy, agricultural \n Topic 2: gardens, restaurants, year, bank, missoula \n Topic 3: like, see, local, food, school \n Topic 4: options, sustainable, grown, available, meat \n Topic 5: food, local, foods, support, produce \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 161 (approx. per word bound = -5.858, relative change = 3.158e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 162 (approx. per word bound = -5.856, relative change = 3.466e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 163 (approx. per word bound = -5.854, relative change = 3.707e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 164 (approx. per word bound = -5.852, relative change = 3.798e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 165 (approx. per word bound = -5.850, relative change = 3.881e-04) \nTopic 1: land, affordable, healthy, locally, agricultural \n Topic 2: gardens, restaurants, year, bank, missoula \n Topic 3: like, see, local, food, school \n Topic 4: sustainable, options, grown, available, meat \n Topic 5: food, local, foods, support, produce \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 166 (approx. per word bound = -5.847, relative change = 3.822e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 167 (approx. per word bound = -5.845, relative change = 3.511e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 168 (approx. per word bound = -5.843, relative change = 3.076e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 169 (approx. per word bound = -5.842, relative change = 2.614e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 170 (approx. per word bound = -5.841, relative change = 2.223e-04) \nTopic 1: land, healthy, agricultural, less, farm \n Topic 2: gardens, community, restaurants, year, bank \n Topic 3: like, see, local, food, school \n Topic 4: affordable, sustainable, options, locally, grown \n Topic 5: food, local, foods, support, produce \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 171 (approx. per word bound = -5.840, relative change = 1.851e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 172 (approx. per word bound = -5.839, relative change = 1.599e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 173 (approx. per word bound = -5.838, relative change = 1.679e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 174 (approx. per word bound = -5.837, relative change = 1.855e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 175 (approx. per word bound = -5.835, relative change = 2.069e-04) \nTopic 1: land, healthy, agricultural, less, farm \n Topic 2: gardens, community, missoula, restaurants, year \n Topic 3: like, local, see, food, school \n Topic 4: affordable, sustainable, options, grown, available \n Topic 5: food, local, foods, support, locally \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 176 (approx. per word bound = -5.834, relative change = 2.348e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 177 (approx. per word bound = -5.832, relative change = 2.587e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 178 (approx. per word bound = -5.831, relative change = 2.118e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 179 (approx. per word bound = -5.830, relative change = 1.411e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 180 (approx. per word bound = -5.830, relative change = 1.017e-04) \nTopic 1: land, healthy, agricultural, less, farm \n Topic 2: gardens, community, missoula, restaurants, year \n Topic 3: local, like, see, food, school \n Topic 4: affordable, sustainable, options, grown, stores \n Topic 5: food, local, foods, locally, support \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 181 (approx. per word bound = -5.829, relative change = 8.410e-05) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 182 (approx. per word bound = -5.829, relative change = 7.340e-05) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 183 (approx. per word bound = -5.829, relative change = 6.714e-05) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 184 (approx. per word bound = -5.828, relative change = 6.060e-05) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 185 (approx. per word bound = -5.828, relative change = 5.365e-05) \nTopic 1: land, healthy, agricultural, less, farm \n Topic 2: gardens, community, missoula, restaurants, year \n Topic 3: local, like, see, food, school \n Topic 4: affordable, sustainable, options, grown, stores \n Topic 5: food, local, locally, foods, support \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 186 (approx. per word bound = -5.828, relative change = 4.610e-05) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 187 (approx. per word bound = -5.827, relative change = 3.855e-05) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 188 (approx. per word bound = -5.827, relative change = 3.679e-05) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 189 (approx. per word bound = -5.827, relative change = 4.987e-05) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 190 (approx. per word bound = -5.826, relative change = 9.302e-05) \nTopic 1: land, healthy, agricultural, less, farm \n Topic 2: gardens, community, missoula, restaurants, year \n Topic 3: local, like, see, food, school \n Topic 4: affordable, sustainable, options, grown, stores \n Topic 5: food, local, locally, foods, support \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 191 (approx. per word bound = -5.826, relative change = 1.224e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 192 (approx. per word bound = -5.825, relative change = 1.107e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 193 (approx. per word bound = -5.824, relative change = 8.373e-05) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 194 (approx. per word bound = -5.824, relative change = 7.585e-05) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 195 (approx. per word bound = -5.824, relative change = 7.365e-05) \nTopic 1: land, healthy, agricultural, less, farm \n Topic 2: gardens, community, restaurants, year, missoula \n Topic 3: local, like, see, food, school \n Topic 4: affordable, sustainable, options, grown, stores \n Topic 5: food, local, locally, foods, support \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 196 (approx. per word bound = -5.823, relative change = 6.859e-05) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 197 (approx. per word bound = -5.823, relative change = 6.565e-05) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 198 (approx. per word bound = -5.822, relative change = 6.767e-05) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 199 (approx. per word bound = -5.822, relative change = 7.497e-05) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 200 (approx. per word bound = -5.821, relative change = 8.404e-05) \nTopic 1: land, healthy, agricultural, farm, less \n Topic 2: gardens, community, restaurants, year, missoula \n Topic 3: local, like, see, food, school \n Topic 4: affordable, sustainable, options, grown, stores \n Topic 5: food, local, locally, foods, support \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 201 (approx. per word bound = -5.821, relative change = 9.158e-05) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 202 (approx. per word bound = -5.820, relative change = 1.006e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 203 (approx. per word bound = -5.820, relative change = 1.028e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 204 (approx. per word bound = -5.819, relative change = 8.944e-05) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 205 (approx. per word bound = -5.819, relative change = 6.783e-05) \nTopic 1: land, healthy, agricultural, farm, less \n Topic 2: gardens, community, restaurants, year, missoula \n Topic 3: local, like, see, food, school \n Topic 4: affordable, sustainable, options, grown, farm \n Topic 5: food, local, locally, foods, support \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 206 (approx. per word bound = -5.819, relative change = 5.699e-05) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 207 (approx. per word bound = -5.818, relative change = 5.934e-05) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 208 (approx. per word bound = -5.818, relative change = 7.214e-05) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 209 (approx. per word bound = -5.817, relative change = 9.343e-05) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 210 (approx. per word bound = -5.817, relative change = 1.075e-04) \nTopic 1: land, healthy, agricultural, less, farm \n Topic 2: gardens, community, restaurants, year, missoula \n Topic 3: local, like, food, see, school \n Topic 4: affordable, options, sustainable, grown, farm \n Topic 5: food, local, locally, foods, support \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 211 (approx. per word bound = -5.816, relative change = 8.615e-05) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 212 (approx. per word bound = -5.816, relative change = 5.559e-05) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 213 (approx. per word bound = -5.815, relative change = 4.838e-05) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 214 (approx. per word bound = -5.815, relative change = 5.664e-05) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 215 (approx. per word bound = -5.815, relative change = 7.047e-05) \nTopic 1: land, healthy, agricultural, less, farm \n Topic 2: gardens, community, restaurants, year, missoula \n Topic 3: local, like, food, see, school \n Topic 4: affordable, options, sustainable, grown, farm \n Topic 5: food, local, locally, foods, support \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 216 (approx. per word bound = -5.814, relative change = 9.000e-05) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 217 (approx. per word bound = -5.814, relative change = 1.084e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 218 (approx. per word bound = -5.813, relative change = 1.206e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 219 (approx. per word bound = -5.812, relative change = 1.251e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 220 (approx. per word bound = -5.811, relative change = 1.239e-04) \nTopic 1: land, healthy, agricultural, less, farm \n Topic 2: gardens, community, year, restaurants, missoula \n Topic 3: local, like, food, see, school \n Topic 4: affordable, options, grown, sustainable, farm \n Topic 5: food, local, locally, foods, support \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 221 (approx. per word bound = -5.811, relative change = 1.243e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 222 (approx. per word bound = -5.810, relative change = 1.303e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 223 (approx. per word bound = -5.809, relative change = 1.402e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 224 (approx. per word bound = -5.808, relative change = 1.577e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 225 (approx. per word bound = -5.807, relative change = 1.923e-04) \nTopic 1: land, healthy, agricultural, less, farm \n Topic 2: gardens, community, year, restaurants, missoula \n Topic 3: local, like, see, food, school \n Topic 4: affordable, options, grown, farm, stores \n Topic 5: food, local, locally, foods, support \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 226 (approx. per word bound = -5.806, relative change = 2.405e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 227 (approx. per word bound = -5.804, relative change = 2.806e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 228 (approx. per word bound = -5.803, relative change = 2.638e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 229 (approx. per word bound = -5.802, relative change = 1.826e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 230 (approx. per word bound = -5.801, relative change = 1.161e-04) \nTopic 1: land, healthy, food, agricultural, less \n Topic 2: gardens, community, year, restaurants, missoula \n Topic 3: local, like, see, food, school \n Topic 4: affordable, options, grown, farm, stores \n Topic 5: food, local, locally, foods, sustainable \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 231 (approx. per word bound = -5.800, relative change = 9.353e-05) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 232 (approx. per word bound = -5.800, relative change = 8.224e-05) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 233 (approx. per word bound = -5.799, relative change = 7.602e-05) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 234 (approx. per word bound = -5.799, relative change = 7.695e-05) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 235 (approx. per word bound = -5.798, relative change = 9.128e-05) \nTopic 1: land, food, healthy, agricultural, less \n Topic 2: gardens, community, year, restaurants, missoula \n Topic 3: local, like, see, food, school \n Topic 4: affordable, options, grown, stores, farm \n Topic 5: food, local, locally, foods, sustainable \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 236 (approx. per word bound = -5.798, relative change = 1.373e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 237 (approx. per word bound = -5.796, relative change = 2.390e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 238 (approx. per word bound = -5.795, relative change = 2.660e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 239 (approx. per word bound = -5.794, relative change = 1.739e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 240 (approx. per word bound = -5.793, relative change = 1.609e-04) \nTopic 1: land, food, healthy, agricultural, farm \n Topic 2: food, gardens, community, year, restaurants \n Topic 3: local, like, food, see, school \n Topic 4: affordable, options, grown, stores, farm \n Topic 5: food, local, locally, foods, sustainable \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 241 (approx. per word bound = -5.792, relative change = 1.635e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 242 (approx. per word bound = -5.791, relative change = 1.603e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 243 (approx. per word bound = -5.790, relative change = 1.430e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 244 (approx. per word bound = -5.789, relative change = 1.293e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 245 (approx. per word bound = -5.788, relative change = 1.436e-04) \nTopic 1: land, food, healthy, agricultural, farm \n Topic 2: food, gardens, community, year, restaurants \n Topic 3: local, like, food, see, school \n Topic 4: affordable, options, grown, stores, farm \n Topic 5: food, local, locally, foods, sustainable \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 246 (approx. per word bound = -5.788, relative change = 1.375e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 247 (approx. per word bound = -5.787, relative change = 9.034e-05) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 248 (approx. per word bound = -5.787, relative change = 5.375e-05) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 249 (approx. per word bound = -5.787, relative change = 3.663e-05) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 250 (approx. per word bound = -5.786, relative change = 2.794e-05) \nTopic 1: land, food, healthy, less, agricultural \n Topic 2: food, gardens, community, year, restaurants \n Topic 3: local, like, food, see, school \n Topic 4: affordable, options, grown, stores, farm \n Topic 5: food, local, locally, foods, sustainable \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 251 (approx. per word bound = -5.786, relative change = 1.981e-05) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 252 (approx. per word bound = -5.786, relative change = 1.531e-05) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 253 (approx. per word bound = -5.786, relative change = 1.636e-05) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 254 (approx. per word bound = -5.786, relative change = 2.316e-05) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 255 (approx. per word bound = -5.786, relative change = 3.823e-05) \nTopic 1: land, food, healthy, less, agricultural \n Topic 2: food, gardens, community, year, restaurants \n Topic 3: local, like, food, see, school \n Topic 4: affordable, options, grown, stores, farm \n Topic 5: food, local, locally, foods, sustainable \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 256 (approx. per word bound = -5.785, relative change = 5.906e-05) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 257 (approx. per word bound = -5.785, relative change = 9.515e-05) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 258 (approx. per word bound = -5.784, relative change = 1.183e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 259 (approx. per word bound = -5.784, relative change = 9.960e-05) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 260 (approx. per word bound = -5.783, relative change = 7.767e-05) \nTopic 1: land, food, healthy, less, farm \n Topic 2: food, gardens, community, year, restaurants \n Topic 3: local, food, like, see, school \n Topic 4: affordable, options, grown, farm, stores \n Topic 5: food, local, locally, sustainable, foods \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 261 (approx. per word bound = -5.783, relative change = 5.896e-05) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 262 (approx. per word bound = -5.783, relative change = 5.309e-05) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 263 (approx. per word bound = -5.782, relative change = 5.069e-05) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 264 (approx. per word bound = -5.782, relative change = 4.914e-05) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 265 (approx. per word bound = -5.782, relative change = 6.084e-05) \nTopic 1: land, food, healthy, farm, less \n Topic 2: food, gardens, community, year, restaurants \n Topic 3: local, food, like, see, school \n Topic 4: affordable, options, grown, farm, stores \n Topic 5: food, local, locally, sustainable, foods \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 266 (approx. per word bound = -5.781, relative change = 9.901e-05) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 267 (approx. per word bound = -5.780, relative change = 1.423e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 268 (approx. per word bound = -5.779, relative change = 1.547e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 269 (approx. per word bound = -5.779, relative change = 1.415e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 270 (approx. per word bound = -5.778, relative change = 1.541e-04) \nTopic 1: land, food, healthy, farm, less \n Topic 2: food, gardens, community, year, missoula \n Topic 3: local, food, like, see, school \n Topic 4: affordable, options, grown, farm, stores \n Topic 5: food, local, locally, sustainable, foods \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 271 (approx. per word bound = -5.777, relative change = 1.667e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 272 (approx. per word bound = -5.776, relative change = 1.356e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 273 (approx. per word bound = -5.775, relative change = 1.225e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 274 (approx. per word bound = -5.774, relative change = 1.401e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 275 (approx. per word bound = -5.774, relative change = 1.198e-04) \nTopic 1: land, food, healthy, farm, less \n Topic 2: food, gardens, community, year, missoula \n Topic 3: local, food, like, see, school \n Topic 4: affordable, options, grown, stores, farm \n Topic 5: food, local, locally, sustainable, foods \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 276 (approx. per word bound = -5.773, relative change = 8.704e-05) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 277 (approx. per word bound = -5.773, relative change = 8.326e-05) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 278 (approx. per word bound = -5.772, relative change = 1.098e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 279 (approx. per word bound = -5.771, relative change = 1.480e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 280 (approx. per word bound = -5.770, relative change = 1.252e-04) \nTopic 1: land, food, healthy, farm, less \n Topic 2: food, gardens, community, year, missoula \n Topic 3: local, food, like, see, school \n Topic 4: affordable, options, grown, stores, farm \n Topic 5: local, food, locally, sustainable, foods \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 281 (approx. per word bound = -5.770, relative change = 8.711e-05) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 282 (approx. per word bound = -5.769, relative change = 9.696e-05) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 283 (approx. per word bound = -5.769, relative change = 1.148e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 284 (approx. per word bound = -5.768, relative change = 9.429e-05) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 285 (approx. per word bound = -5.768, relative change = 8.107e-05) \nTopic 1: land, food, healthy, farm, less \n Topic 2: food, gardens, community, year, missoula \n Topic 3: local, food, like, see, school \n Topic 4: affordable, options, grown, stores, farm \n Topic 5: local, food, locally, sustainable, foods \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 286 (approx. per word bound = -5.767, relative change = 7.845e-05) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 287 (approx. per word bound = -5.767, relative change = 8.266e-05) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 288 (approx. per word bound = -5.766, relative change = 1.009e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 289 (approx. per word bound = -5.766, relative change = 1.099e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 290 (approx. per word bound = -5.765, relative change = 1.032e-04) \nTopic 1: food, land, healthy, less, agricultural \n Topic 2: food, gardens, community, year, missoula \n Topic 3: local, food, like, see, school \n Topic 4: affordable, options, grown, food, stores \n Topic 5: local, food, locally, sustainable, foods \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 291 (approx. per word bound = -5.764, relative change = 1.108e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 292 (approx. per word bound = -5.764, relative change = 1.302e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 293 (approx. per word bound = -5.763, relative change = 1.509e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 294 (approx. per word bound = -5.762, relative change = 1.627e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 295 (approx. per word bound = -5.761, relative change = 1.611e-04) \nTopic 1: food, land, healthy, less, agricultural \n Topic 2: food, gardens, community, local, year \n Topic 3: local, food, like, see, school \n Topic 4: affordable, options, food, local, stores \n Topic 5: local, food, locally, sustainable, foods \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 296 (approx. per word bound = -5.760, relative change = 1.471e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 297 (approx. per word bound = -5.759, relative change = 1.302e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 298 (approx. per word bound = -5.759, relative change = 1.168e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 299 (approx. per word bound = -5.758, relative change = 1.003e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 300 (approx. per word bound = -5.758, relative change = 8.914e-05) \nTopic 1: food, land, healthy, farm, less \n Topic 2: food, local, gardens, community, year \n Topic 3: local, food, like, see, school \n Topic 4: affordable, options, food, local, stores \n Topic 5: food, local, locally, sustainable, foods \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 301 (approx. per word bound = -5.757, relative change = 1.291e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 302 (approx. per word bound = -5.756, relative change = 2.023e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 303 (approx. per word bound = -5.755, relative change = 1.325e-04) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 304 (approx. per word bound = -5.755, relative change = 3.980e-05) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 305 (approx. per word bound = -5.755, relative change = 1.831e-05) \nTopic 1: food, land, healthy, farm, less \n Topic 2: food, local, gardens, community, year \n Topic 3: local, food, like, see, school \n Topic 4: affordable, options, food, local, stores \n Topic 5: food, local, locally, sustainable, foods \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nCompleting Iteration 306 (approx. per word bound = -5.754, relative change = 1.113e-05) \n...........................................................................................................\nCompleted E-Step (0 seconds). \nCompleted M-Step. \nModel Converged \n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# label topics\nlabelTopics(stm_change)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nTopic 1 Top Words:\n \t Highest Prob: food, land, healthy, farm, less, agricultural, use \n \t FREX: healthy, change, less, use, stands, opportunities, agricultural \n \t Lift: 1, 10, acquisition, advocacy, alleviate, along, among \n \t Score: healthy, agricultural, among, evidence-based, might, ag, use \nTopic 2 Top Words:\n \t Highest Prob: food, local, gardens, community, year, missoula, markets \n \t FREX: year, round, gardens, county, bank, production, need \n \t Lift: round, #11, 2-5x, ability, adapted, allowing, always \n \t Score: gardens, year, boulevards, feeding, progress, double, cans \nTopic 3 Top Words:\n \t Highest Prob: local, food, like, see, school, farmers, good \n \t FREX: school, organic, preserve, prices, important, nutrition, good \n \t Lift: -or, $, 5-, abundant, actually, additional, address \n \t Score: poor, section, good, organic, crop, lose, pandemic \nTopic 4 Top Words:\n \t Highest Prob: affordable, options, food, local, stores, farming, farm \n \t FREX: farming, neighborhoods, gardening, affordable, dairy, options, stores \n \t Lift: accessed, activities, adaptation, affordablity, allowed, apartments, appalling \n \t Score: csa, neighborhoods, farming, livestock, shares, example, gardening \nTopic 5 Top Words:\n \t Highest Prob: food, local, locally, sustainable, foods, produce, grown \n \t FREX: sourced, greater, sustainable, locally, afford, foods, away \n \t Lift: sourced, +, 1,000, adults, alone, amazing, amounts \n \t Score: composting, locally, sourced, missoulians, farmer's, really, extra \n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(stm_change, type = \"summary\")\n```\n\n::: {.cell-output-display}\n![](ClaireBattaglia_blogpost5_files/figure-html/plot stm-1.png){width=672}\n:::\n:::\n\n\nThis is interesting. \"Food\" appears in all of the topics. This isn't surprising but I wonder how meaningful its inclusion here is. It might be more interesting to remove it when creating my DFM and see what other words surface once it's been removed. Given the question I think it's safe to assume that every topic *should* have something to do with food.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# estimate effects of income\nincome_effects <- estimateEffect(formula = 1:k ~ income,\n                               stmobj = stm_change,\n                               metadata = CFA_tidy_2)\n\n# get summary\nsummary(income_effects)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nestimateEffect(formula = 1:k ~ income, stmobj = stm_change, metadata = CFA_tidy_2)\n\n\nTopic 1:\n\nCoefficients:\n                                   Estimate Std. Error t value Pr(>|t|)    \n(Intercept)                        0.173989   0.034120   5.099 7.65e-07 ***\nincomeBetween $25,000 and $34,999 -0.042526   0.065160  -0.653    0.515    \nincomeBetween $35,000 and $49,999 -0.011932   0.054842  -0.218    0.828    \nincomeBetween $50,000 and $99,999 -0.007934   0.046939  -0.169    0.866    \nincomeOver $250,000               -0.055561   0.102295  -0.543    0.588    \nincomeUnder $25,000               -0.033044   0.057761  -0.572    0.568    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n\nTopic 2:\n\nCoefficients:\n                                   Estimate Std. Error t value Pr(>|t|)    \n(Intercept)                        0.161971   0.039882   4.061 6.91e-05 ***\nincomeBetween $25,000 and $34,999  0.027549   0.076936   0.358    0.721    \nincomeBetween $35,000 and $49,999 -0.002209   0.063204  -0.035    0.972    \nincomeBetween $50,000 and $99,999  0.080134   0.055691   1.439    0.152    \nincomeOver $250,000                0.060960   0.115542   0.528    0.598    \nincomeUnder $25,000                0.025646   0.073821   0.347    0.729    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n\nTopic 3:\n\nCoefficients:\n                                   Estimate Std. Error t value Pr(>|t|)    \n(Intercept)                        0.194835   0.043319   4.498 1.14e-05 ***\nincomeBetween $25,000 and $34,999 -0.037454   0.077509  -0.483    0.629    \nincomeBetween $35,000 and $49,999  0.018954   0.068590   0.276    0.783    \nincomeBetween $50,000 and $99,999  0.052418   0.058055   0.903    0.368    \nincomeOver $250,000                0.002476   0.114926   0.022    0.983    \nincomeUnder $25,000               -0.001437   0.075003  -0.019    0.985    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n\nTopic 4:\n\nCoefficients:\n                                  Estimate Std. Error t value Pr(>|t|)    \n(Intercept)                        0.21885    0.04235   5.167 5.56e-07 ***\nincomeBetween $25,000 and $34,999 -0.01658    0.07820  -0.212    0.832    \nincomeBetween $35,000 and $49,999 -0.03032    0.06595  -0.460    0.646    \nincomeBetween $50,000 and $99,999 -0.05842    0.05384  -1.085    0.279    \nincomeOver $250,000               -0.05858    0.11208  -0.523    0.602    \nincomeUnder $25,000               -0.01007    0.06882  -0.146    0.884    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n\nTopic 5:\n\nCoefficients:\n                                  Estimate Std. Error t value Pr(>|t|)    \n(Intercept)                        0.25146    0.04309   5.836 2.03e-08 ***\nincomeBetween $25,000 and $34,999  0.06704    0.08314   0.806    0.421    \nincomeBetween $35,000 and $49,999  0.02438    0.06808   0.358    0.721    \nincomeBetween $50,000 and $99,999 -0.06646    0.05722  -1.161    0.247    \nincomeOver $250,000                0.04986    0.11782   0.423    0.673    \nincomeUnder $25,000                0.01830    0.07828   0.234    0.815    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n\n```{.r .cell-code}\n# estimate effects of ZIP Code\nzip_effects <- estimateEffect(formula = 1:k ~ zip,\n                               stmobj = stm_change,\n                               metadata = CFA_tidy_2)\n\n# get summary\nsummary(zip_effects)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nestimateEffect(formula = 1:k ~ zip, stmobj = stm_change, metadata = CFA_tidy_2)\n\n\nTopic 1:\n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)\n(Intercept)  0.047284   0.226465   0.209    0.835\nzip59801     0.128917   0.227357   0.567    0.571\nzip59802     0.056216   0.227410   0.247    0.805\nzip59803     0.076156   0.230103   0.331    0.741\nzip59804     0.245958   0.238414   1.032    0.304\nzip59808     0.128687   0.234228   0.549    0.583\nzip59821     0.017701   0.322728   0.055    0.956\nzip59823     0.112361   0.255864   0.439    0.661\nzip59825     0.282891   0.262923   1.076    0.283\nzip59826     0.584634   0.398729   1.466    0.144\nzip59833     0.050504   0.286555   0.176    0.860\nzip59846     0.062443   0.333407   0.187    0.852\nzip59847     0.040767   0.249218   0.164    0.870\nzip59860     0.067032   0.324538   0.207    0.837\nzip59864     0.384652   0.425122   0.905    0.367\nzip59868    -0.001594   0.320286  -0.005    0.996\nzip59908     0.010186   0.318329   0.032    0.975\n\n\nTopic 2:\n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)  \n(Intercept)  0.0183219  0.2647031   0.069   0.9449  \nzip59801     0.1882929  0.2669918   0.705   0.4815  \nzip59802     0.1794583  0.2675874   0.671   0.5032  \nzip59803     0.1508941  0.2740320   0.551   0.5825  \nzip59804     0.2561032  0.2876342   0.890   0.3743  \nzip59808     0.1085630  0.2745892   0.395   0.6930  \nzip59821    -0.0095976  0.3759561  -0.026   0.9797  \nzip59823     0.0535869  0.2913610   0.184   0.8543  \nzip59825     0.0487810  0.3022978   0.161   0.8720  \nzip59826     0.1606548  0.4229671   0.380   0.7045  \nzip59833     0.0104080  0.3263086   0.032   0.9746  \nzip59846    -0.0001806  0.3807462   0.000   0.9996  \nzip59847     0.2805603  0.3025220   0.927   0.3549  \nzip59860     0.0776642  0.3861748   0.201   0.8408  \nzip59864     0.1999277  0.4290477   0.466   0.6417  \nzip59868     0.6122860  0.4407218   1.389   0.1663  \nzip59908     0.8174844  0.4095763   1.996   0.0473 *\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n\nTopic 3:\n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)  \n(Intercept)  0.80799    0.32730   2.469   0.0144 *\nzip59801    -0.56924    0.33027  -1.724   0.0864 .\nzip59802    -0.59233    0.32476  -1.824   0.0697 .\nzip59803    -0.59469    0.33761  -1.761   0.0797 .\nzip59804    -0.74521    0.34447  -2.163   0.0317 *\nzip59808    -0.71252    0.33986  -2.097   0.0373 *\nzip59821    -0.03856    0.48573  -0.079   0.9368  \nzip59823    -0.63149    0.36760  -1.718   0.0874 .\nzip59825    -0.44730    0.36442  -1.227   0.2211  \nzip59826    -0.75388    0.43272  -1.742   0.0830 .\nzip59833    -0.42776    0.39593  -1.080   0.2813  \nzip59846    -0.52952    0.45800  -1.156   0.2490  \nzip59847    -0.73053    0.35510  -2.057   0.0410 *\nzip59860    -0.70640    0.44457  -1.589   0.1137  \nzip59864    -0.74791    0.43067  -1.737   0.0840 .\nzip59868    -0.76562    0.44198  -1.732   0.0848 .\nzip59908    -0.79983    0.43064  -1.857   0.0648 .\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n\nTopic 4:\n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)\n(Intercept)  0.038349   0.265003   0.145    0.885\nzip59801     0.138035   0.266432   0.518    0.605\nzip59802     0.142551   0.268993   0.530    0.597\nzip59803     0.143104   0.275537   0.519    0.604\nzip59804     0.136616   0.284789   0.480    0.632\nzip59808     0.356098   0.280249   1.271    0.205\nzip59821     0.039878   0.378015   0.105    0.916\nzip59823     0.192161   0.298811   0.643    0.521\nzip59825     0.001799   0.294552   0.006    0.995\nzip59826     0.005270   0.377750   0.014    0.989\nzip59833     0.327671   0.342464   0.957    0.340\nzip59846     0.071641   0.406786   0.176    0.860\nzip59847     0.201905   0.305044   0.662    0.509\nzip59860     0.049648   0.407036   0.122    0.903\nzip59864     0.054941   0.386516   0.142    0.887\nzip59868     0.149849   0.398199   0.376    0.707\nzip59908    -0.010570   0.374368  -0.028    0.978\n\n\nTopic 5:\n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)\n(Intercept)  0.088206   0.295323   0.299    0.766\nzip59801     0.113967   0.298747   0.381    0.703\nzip59802     0.215087   0.298387   0.721    0.472\nzip59803     0.224355   0.300177   0.747    0.456\nzip59804     0.103216   0.317330   0.325    0.745\nzip59808     0.119917   0.305285   0.393    0.695\nzip59821    -0.013396   0.417811  -0.032    0.974\nzip59823     0.272868   0.323560   0.843    0.400\nzip59825     0.111239   0.332682   0.334    0.738\nzip59826     0.002980   0.410396   0.007    0.994\nzip59833     0.039520   0.371567   0.106    0.915\nzip59846     0.383000   0.446201   0.858    0.392\nzip59847     0.204348   0.339214   0.602    0.548\nzip59860     0.514118   0.444564   1.156    0.249\nzip59864     0.111071   0.422243   0.263    0.793\nzip59868     0.004107   0.400220   0.010    0.992\nzip59908    -0.017016   0.413857  -0.041    0.967\n```\n:::\n:::\n\n\nIt appears that each income bracket is slightly positively or negatively associated with each of the five topics but that none of these associations are statistically significant. There are some statistically significant associations between some of the ZIP Codes and particular topics. However, given that I am still exploring how to preprocess my corpus into a DFM and the appropriate number of topics, I am not considering this analysis to be final. Ultimately, the sample is such (too small, not distributed over income brackets and ZIP Codes--some of the ZIP Codes have one respondent!) that it will preclude me from drawing any firm conclusions about associations anyway.\n\n## Challenges and Questions Moving Forward\n\nOne challenge with topic modeling is that it is up to the researcher to decide how many topics (*k*) to include in the model. I have no sense of how to do this. Given that the corpus I am working with right now is only a few hundred short documents, I could count them manually but that will not always be feasible. It seems that the best practice is to build models with several different values for *k* and use various methods to evaluate those models.\n\nIn addition to thinking about how to tweak my DFM to make the results of my analysis more revealing, I also need to learn how to evaluate my models to determine which is the most appropriate. Related to that, I need to figure out how to visualize my results.\n\n\n\n\n\n\n\n\n\n\n\n",
    "supporting": [
      "ClaireBattaglia_blogpost5_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}