{
  "hash": "9a838741fc5c8bf169608500b4133a1b",
  "result": {
    "markdown": "---\ntitle: \"Mapping Feminist Stories: finding data\"\nauthor: \"Leah Dion\"\ndesription: \"My initial exploration of data downloaded from JSTOR and Constellate.\"\ndate: \"10/27/2022\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - hw2\n  - leah dion\n  - jsonl files\n  - JSTOR\n---\n\n::: {.cell}\n\n:::\n\n\n### Research\n\nUsing Clare Hemmings' textual analysis from *Why Stories Matter* as a guide, I have two main questions in mind to my research:\n\n1.  How does Hemmings' argument about the stories told in the gloss of a selection of feminist journal articles compare when applied to a larger body of text from the same feminist journals?\n2.  Using the January 2011 publication of *Why Stories Matter* and Hemmings' paper from 2005, \"Telling Feminist Stories\", as markers in time, have there been any shifts in citation tactics in feminist journal articles?\n\nTo answer these questions I will use several methods offered by Hemmings in her book. The primary of these is her use of citation tactics, which includes comparing text across journals rather than by individual authors. She emphasizes this as \"a way of foregrounding knowledge practices as shared rather than individual\" (21). Since feminist theory -- and arguably theory in general -- exists as a result of overlapping dialogues of thought, an attention to the cumulative impacts of the text itself resists the urge to centralize any singular writer; an important objective of feminist theory and Hemmings' argument in whole.\n\nClare Hemmings' approach congeals around citation as she indicates \"it anchors an overall chronology, provides a semblance of detail, and has an appropriate status as evidence\" (22) of the narrativization she highlights. In practice, this means citing journals and years of publication rather than the author of each article to attend to the collective repetition of narratives. In my analysis I will thus focus on the collective knowledge production of journals over the work of individual authors when gathering inferences and making comparisons.\n\n### Initial attempt\n\nBefore I narrowed the scope of my project, I initially attempted to download a PDF file of Clare Hemmings' book *Why Stories Matter* to determine if PDF-to-text would be a feasible approach. This would allow me to control how to parse the text and build a corpus that matches my research objectives.\n\nI downloaded the chapter files from the JSTOR database and loaded them into R using the `pdftools` package.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# extract file names\nfiles <- list.files(path = \"./Hemmings\", pattern = \"pdf$\")\n\n# get chapter text\nchapters <- lapply(here(\"posts\", \"Hemmings\", files), pdf_text)\nhem_corp <- Corpus(URISource(here(\"posts\", \"Hemmings\", files)), \n                   readerControl = list(reader = readPDF))\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nPDF error: xref num 2 not found but needed, try to reconstruct<0a>\nPDF error: xref num 2 not found but needed, try to reconstruct<0a>\nPDF error: xref num 2 not found but needed, try to reconstruct<0a>\nPDF error: xref num 2 not found but needed, try to reconstruct<0a>\nPDF error: xref num 2 not found but needed, try to reconstruct<0a>\nPDF error: xref num 2 not found but needed, try to reconstruct<0a>\nPDF error: xref num 2 not found but needed, try to reconstruct<0a>\nPDF error: xref num 2 not found but needed, try to reconstruct<0a>\nPDF error: xref num 2 not found but needed, try to reconstruct<0a>\n```\n:::\n\n```{.r .cell-code}\n# view one page of text\nchapters[[1]][3]\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"192           ratives of progress, loss, and return. Western feminist return narratives are\\n              particularly interesting in this respect, insofar as they allow an affective\\nChapter Six\\n\\n\\n\\n              resolution to these contests over history, meaning, and subjectivity. Re-\\n              turn narratives allow the feminist present to be shared by subjects with\\n              different readings of the same history, with one prerequisite: that each\\n              subject acknowledge that her own singular position was previously too\\n              emphatic, lacked nuance, and now needs revision.\\n                  To restate this argument brieﬂy, return narratives ask subjects of West-\\n              ern feminist progress narratives to admit that they may have been too\\n              hasty in rejecting earlier approaches as essentialist and to acknowledge\\n              that important feminist political insights have been lost, while they ask\\n              subjects of loss narratives to admit that they were too hasty in dismissing\\n              important critiques of essentialism’s exclusions. Theoretical and political\\n              resolution in return narratives relies on agreement that the cultural turn\\n              was an abstraction too far, and requires mediation of the twinned affects\\n              of hope and despair that characterize progress and loss narratives respec-\\n              tively. In return narratives, then, a broader range of feminist subjects can\\n              occupy the Western feminist present, but only on the basis of a shared\\n              sense of what has come before. As discussed throughout this book thus far,\\n              the affective manifestations of this historiographic investment are a shared\\n              sense of loss at feminism’s demise and a shared hope that a reinvigorated\\n              feminism may be possible in the future. That the subjects of that future\\n              feminism will be the same as those concerned with its progress or loss now\\n              is never questioned. Indeed, so strong is the attachment to the subject of a\\n              Western feminist return narrative being the one to reinvigorate feminist\\n              theory and politics that the twinned affects of keen loss and muted hope\\n              that underwrite this history are set on textual replay, lest other perceptions\\n              of the past and present suggest a different future.\\n                  Further, as I argued in chapter 4, ‘‘Amenability,’’ the narrative insistence\\n              on feminism being over and in need of recovery in the familiar, slightly\\n              altered, form that marks return narratives means that the distinction be-\\n              tween postfeminist discourses and Western feminist stories about our own\\n              recent past comes to rest on the overburdened signiﬁcance of that feminist\\n              subject. If these overlapping narrations of the social world coincide in\\n              terms of their historical markers and juxtapositions, the difference must lie\\n              in the feminist subject’s capacity to reinvigorate rather than abandon what\\n              has come before. The difference between a progressive agenda and co-\\n\\n\\n\\n\\n                 This content downloaded from 128.119.168.112 on Mon, 26 Sep 2022 19:44:21 UTC\\n                                   All use subject to https://about.jstor.org/terms\\n\"\n```\n:::\n:::\n\n\nThe above text is page three of chapter one and gives a brief sample of the processing required to get the text in to a usable format. First of all, at the bottom of each page is a timestamp which marks the time each file was downloaded from the JSTOR database.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchapters[[1]][3] %>%\nstr_remove_all(\"This content downloaded from 128.119.168.112 on Mon, 26 Sep 2022 19:44:21 UTC\") %>%\n  str_remove_all(\"All use subject to https://about.jstor.org/terms\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"192           ratives of progress, loss, and return. Western feminist return narratives are\\n              particularly interesting in this respect, insofar as they allow an affective\\nChapter Six\\n\\n\\n\\n              resolution to these contests over history, meaning, and subjectivity. Re-\\n              turn narratives allow the feminist present to be shared by subjects with\\n              different readings of the same history, with one prerequisite: that each\\n              subject acknowledge that her own singular position was previously too\\n              emphatic, lacked nuance, and now needs revision.\\n                  To restate this argument brieﬂy, return narratives ask subjects of West-\\n              ern feminist progress narratives to admit that they may have been too\\n              hasty in rejecting earlier approaches as essentialist and to acknowledge\\n              that important feminist political insights have been lost, while they ask\\n              subjects of loss narratives to admit that they were too hasty in dismissing\\n              important critiques of essentialism’s exclusions. Theoretical and political\\n              resolution in return narratives relies on agreement that the cultural turn\\n              was an abstraction too far, and requires mediation of the twinned affects\\n              of hope and despair that characterize progress and loss narratives respec-\\n              tively. In return narratives, then, a broader range of feminist subjects can\\n              occupy the Western feminist present, but only on the basis of a shared\\n              sense of what has come before. As discussed throughout this book thus far,\\n              the affective manifestations of this historiographic investment are a shared\\n              sense of loss at feminism’s demise and a shared hope that a reinvigorated\\n              feminism may be possible in the future. That the subjects of that future\\n              feminism will be the same as those concerned with its progress or loss now\\n              is never questioned. Indeed, so strong is the attachment to the subject of a\\n              Western feminist return narrative being the one to reinvigorate feminist\\n              theory and politics that the twinned affects of keen loss and muted hope\\n              that underwrite this history are set on textual replay, lest other perceptions\\n              of the past and present suggest a different future.\\n                  Further, as I argued in chapter 4, ‘‘Amenability,’’ the narrative insistence\\n              on feminism being over and in need of recovery in the familiar, slightly\\n              altered, form that marks return narratives means that the distinction be-\\n              tween postfeminist discourses and Western feminist stories about our own\\n              recent past comes to rest on the overburdened signiﬁcance of that feminist\\n              subject. If these overlapping narrations of the social world coincide in\\n              terms of their historical markers and juxtapositions, the difference must lie\\n              in the feminist subject’s capacity to reinvigorate rather than abandon what\\n              has come before. The difference between a progressive agenda and co-\\n\\n\\n\\n\\n                 \\n                                   \\n\"\n```\n:::\n:::\n\n\nRemoving the timestamp is not very difficult for each page, but when aggregating to larger and larger datasets (i.e. more text) this approach will likely get more complicated and require a lot of preprocessing to a significant amount of journal articles. Before going further I would like to see if there is an easier datatype to work with than PDFs.\n\n### JSTOR and jsonl files\n\nIt turns out, JSTOR Labs has an open-source text-mining project they call [Constellate](https://about.jstor.org/whats-in-jstor/text-mining-support/) which lets you filter and compile text into a dataset you can download. My first attempt involved importing the entire published history of *Signs, Feminist Review, and Feminist Theory*, three of the six feminist journals utilized by Clare Hemmings in her book.\n\nInitially, I had difficulty reading the file into RStudio. The file type is `jsonl`, which I learned requires a slightly modified approach to getting it into R than a plain `json` file. A `jsonl` file is a file where each line contains a separate `json` file, with `jsonl` meaning 'JSON lines'. In the case of my data, each line represents a different article. The `jsonlite` package contains a function `stream_in`, which will unlist `jsonl` files to import each of the separate `json` files contained within.\n\nMy computer was taking a long time to read in the 9381 documents in my data file, so I downloaded a smaller dataset containing 35 articles published by the journal *Feminist Theory* in 2012 to explore the usefulness of the JSTOR library in my project.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# read file\njson <- stream_in(file(\"dafd16db-9e50-8e9c-007d-d6ab654e2571-sampled-jsonl.jsonl\"))\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nopening file input connection.\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n\n Found 35 records...\n Imported 35 records. Simplifying...\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nclosing file input connection.\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# column names\nnames(json)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1] \"creator\"         \"datePublished\"   \"docType\"         \"doi\"            \n [5] \"id\"              \"identifier\"      \"isPartOf\"        \"issueNumber\"    \n [9] \"keyphrase\"       \"language\"        \"outputFormat\"    \"pageCount\"      \n[13] \"pageEnd\"         \"pageStart\"       \"pagination\"      \"provider\"       \n[17] \"publicationYear\" \"publisher\"       \"sequence\"        \"tdmCategory\"    \n[21] \"title\"           \"url\"             \"volumeNumber\"    \"wordCount\"      \n[25] \"unigramCount\"    \"bigramCount\"     \"trigramCount\"    \"docSubType\"     \n```\n:::\n:::\n\n\nLooking at the first few rows reveals that each row corresponds to one of the 35 articles in the corpus. There are 28 columns in total (above), several of which describe details of the article and publication in general. Many of the variable names are straightforward, such as *datePublished, docType, publisher, title,* etc., but there are a few important ones that could determine the usefulness of this dataset for my research questions.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnames(json)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1] \"creator\"         \"datePublished\"   \"docType\"         \"doi\"            \n [5] \"id\"              \"identifier\"      \"isPartOf\"        \"issueNumber\"    \n [9] \"keyphrase\"       \"language\"        \"outputFormat\"    \"pageCount\"      \n[13] \"pageEnd\"         \"pageStart\"       \"pagination\"      \"provider\"       \n[17] \"publicationYear\" \"publisher\"       \"sequence\"        \"tdmCategory\"    \n[21] \"title\"           \"url\"             \"volumeNumber\"    \"wordCount\"      \n[25] \"unigramCount\"    \"bigramCount\"     \"trigramCount\"    \"docSubType\"     \n```\n:::\n:::\n\n\nThe first of these is *keyphrase*. Looking at the snapshot below, this variable seems to contain ten key phrases for each document. I notice there are numerous names of authors in these terms, which I imagine connects to each article's main arguments and the conversation the article's author is engaging in Some of these are last names only, some are (last first) and others are (first last) and some terms share the same root, so I may want to apply stemming techniques to manage the overlaps. Also, I notice one key phrase in the third article, \"ceremony and ritual\", implying that these likely contain either unigrams, bigrams, or trigrams.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(json$keyphrase)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[[1]]\n [1] \"object lessons\" \"wiegman\"        \"robyn wiegman\"  \"cruel optimism\"\n [5] \"berlant lauren\" \"gender\"         \"studies\"        \"affective\"     \n [9] \"koivunen\"       \"identity\"      \n\n[[2]]\n [1] \"sexual abuse\"         \"memories\"             \"child sexual abuse\"  \n [4] \"sex trafficking\"      \"rape allegations\"     \"childhood sexual\"    \n [7] \"sex workers\"          \"basingstoke palgrave\" \"harm story\"          \n[10] \"stories\"             \n\n[[3]]\n [1] \"parliament\"          \"ritual\"              \"parliamentary\"      \n [4] \"ceremony and ritual\" \"gender\"              \"westminster\"        \n [7] \"performativity\"      \"political\"           \"programme\"          \n[10] \"institutions\"       \n\n[[4]]\n [1] \"sexual\"             \"stefan\"             \"postfeminism\"      \n [4] \"wetlands\"           \"sexual empowerment\" \"empowerment\"       \n [7] \"female\"             \"wave feminism\"      \"verena stefan\"     \n[10] \"bodies\"            \n\n[[5]]\n [1] \"diffractive analysis\"  \"deleuze\"               \"mazzei\"               \n [4] \"material discursive\"   \"becoming minoritarian\" \"minoritarian\"         \n [7] \"thinking\"              \"alaimo\"                \"lisa mazzei\"          \n[10] \"researcher\"           \n\n[[6]]\n [1] \"sexual\"                \"foucault\"              \"feminist media\"       \n [4] \"hermeneutics\"          \"sexual subjecthood\"    \"feminist hermeneutics\"\n [7] \"bodily\"                \"sexual difference\"     \"mcrobbie\"             \n[10] \"adolescence\"          \n```\n:::\n:::\n\n\nThe next potential interesting variable is *tdmCategory*. Expanding the list shows that this contains categorization labels used in the digital archival of these texts. In mapping genealogies, it is often important to understand what discipline a given author is trained and located in as it can offer insights into word and prose choices that could be more reflective of a disciplinary approach than an individual author. As I build my corpus, these categories could be used to summarize the larger journals themselves, identifying which field's perspectives are most commonly published.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(json$tdmCategory)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[[1]]\n[1] \"Philosophy - Applied philosophy\"  \"Philosophy - Axiology\"           \n[3] \"History - Historical methodology\" \"Social sciences - Communications\"\n\n[[2]]\n[1] \"Philosophy - Applied philosophy\"  \"Social sciences - Communications\"\n\n[[3]]\n[1] \"Political science - Politics\"   \"Political science - Government\"\n\n[[4]]\n[1] \"Arts - Literature\"                    \n[2] \"Social sciences - Behavioral sciences\"\n\n[[5]]\n[1] \"Linguistics - Philosophy of language\"\n[2] \"Philosophy - Metaphysics\"            \n[3] \"Philosophy - Applied philosophy\"     \n\n[[6]]\n[1] \"Biological sciences - Biology\"       \n[2] \"Linguistics - Philosophy of language\"\n```\n:::\n:::\n\n\nThe last variables to explore are *unigramCount*, *bigramCount*, and *trigramCount*, which I hope contain the entire text of the articles. Looking at the unigram dataframe below, the dimensions are 35 x 26,618. This means there are nearly 27000 unique words combined in the 35 articles.\n\nHowever, browsing through the column names (i.e. words) reveals that punctuation and capitalization has not been processed, significantly adding to the number of words in the document-term-matrix. Before using these counts I will have to combine and aggregate the counts of each term after adjusting and removing punctuation and capitalization.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndim(json$unigramCount)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1]    35 26618\n```\n:::\n\n```{.r .cell-code}\ndim(json$bigramCount)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1]    35 99323\n```\n:::\n\n```{.r .cell-code}\ndim(json$trigramCount)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1]     35 142305\n```\n:::\n:::\n\n\nChecking the dimensions of the other DTMs, there are 99323 words in \n*bigramCount* and 142305 in *trigramCount*. Processing the raw text would likely give me even more flexibility to check statistics such as how frequently certain words or authors are used in the same sentence. I won't be able to reach that level of granularity with this dataset, but having each of these ngrams in matrix form will help simplify my initial analyses and developing a deeper understanding of the text within.\n\nIn my next blog post, I will begin pre-processing the columns of the ngram matrices to reduce the dimensions and aggregate appropriate word counts.\n\n\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}