---
title: "Topic Modelling"
author: "Adithya Parupudi"
desription: "Topic Modeling attempt"
date: "10/11/2022"
format:
  html:
    toc: true
    code-fold: true
    code-copy: true
    code-tools: true
categories:
  - Adithya Parupudi
---

# Libraries

Reading in all the libraries :)

```{r}
#| label: setup
#| warning: false
library(quanteda)
library(tidyverse)
library(rvest)
library(stringr)
library(tokenizers)
library(tm)
library(wordcloud)
library(wordcloud2)
library(stopwords)
library(tidyverse)
library(tidytext)
library(ggplot2)
knitr::opts_chunk$set(echo=TRUE)
```

# Reading Data

### **From CSV**

```{r}
dataset2 <- read_csv("./100FamousPeople.csv")
head(dataset2)
```

```{r}

dataset2<- tibble(dataset2)



```

```{r}
# counting number of words each row

str_count(dataset2$content, '\\s+')+1


```
# Using STM

```{r}

tidy_dataset <- dataset2 %>% 
  mutate(line=row_number()) %>%  # adding row number
  unnest_tokens(word, content) %>%  # tokenising content column to a 'word' column
  anti_join(stop_words) #removing stop words 

tidy_dataset %>% count(word, sort=TRUE) # countind word frequency in the tidy_dataset

```

## Exploring tf-idf

```{r}


tidy_dataset %>% 
  count(people_names, word, sort=TRUE) %>% 
  bind_tf_idf(word,people_names,n) %>% 
  group_by(people_names) %>% 
  top_n(10) %>% 
  ungroup() %>% 
  mutate(word=reorder(word,tf_idf)) %>% 
  filter(., people_names=='Muhammad Ali' | people_names=='Lionel Messi' | people_names=='Nelson Mandela')  %>% 
  ggplot(aes(word,tf_idf, fill=people_names)) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~people_names, scales="free") +
  coord_flip() 


```
# explore topic modeling

```{r}

library(stm)

tidy_dfm <- tidy_dataset %>% 
  count(people_names, word, sort=TRUE) %>% 
  cast_dfm(people_names, word, n)

topic_model <- stm(tidy_dfm, K = 6, init.type = 'Spectral')



```
```{r}
summary(topic_model)

```
## Beta matrix
```{r}

tidy_beta <- tidy(topic_model)

tidy_beta %>% group_by(topic) %>% 
  top_n(10) %>% 
  ungroup() %>% 
  mutate(term=reorder(term,beta)) %>% 
  ggplot(aes(term,beta, fill=topic)) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~topic, scales="free") +
  coord_flip() 
  

```
# using Gamma matrix

```{r}

tidy_gamma <- tidy(topic_model, matrix="gamma", document_names = rownames(tidy_dfm))


ggplot(tidy_gamma, aes(gamma, fill = as.factor(topic)))+
  geom_histogram(show.legend = FALSE)+
  facet_wrap(~topic, ncol=3)


```


```{r}
```

