---
title: "Blog Post 1"
author: "Kirsten Johnson"
desription: "Identifying my research question"
date: "09/25/2022"
format:
  html:
    toc: true
    code-fold: true
    code-copy: true
    code-tools: true
categories:
  - research question
  - Senitment Analysis
  - Traffic Safety
---

```{r}
#| label: setup
#| warning: false

library(tidyverse)

knitr::opts_chunk$set(echo = TRUE)
```

### Background

Working for the MassDOT Traffic Safety team for the past 2 years, I've had the opportunity to interact with the public and hear their thoughts and concerns surrounding road safety. Specifically, I've assisted in creating and pushing out campaigns and PSAs for various safety topics on social media. The online response on these tweets is typically more negative in tone than positive. However, when comparing the response with other state DOTs, MassDOT seems to receive significantly more negative responses. My research question aims to explore the online public's feelings surrounding traffic safety in Massachusetts.

### Literature Review

#### Sujon & Dai (2021)

Sujon and Dai sought to identify the collective beliefs of traffic safety culture in Washington state. They examined the potential of social media and the techniques of big data mining to understand what the shared values, beliefs, and attitudes are most influential to drivers' behavior.The specific research objectives of their research were to:

1.  Analyze the public's general sentiments toward traffic safety.

2.  Analyze specific points of view toward high-risk driving behaviors as outlined in Washington's Target Zero plan.

3.  Identify key cultural determinants that stimulate these high-risk behaviors.

The authors developed questions that address people's attitudes towards different aspects of safety as measures to guide the data analysis. The data used were tweets collected from March 2015 to February 2019 that were generated in the state of Washington and contained keywords. Keywords were identified by referencing traffic safety--related publications, websites, and social media pages. Based on the number of tweets collected for each keyword and phrase, a list of keywords and phrases was created and classified based on their frequency. Data were cleaned via a text removal approach. Stop words, unimportant punctuation, and non-sentimental numbers and special characters were removed in order to improve accuracy. This research did not use bot removal to exclude bot account--generated tweets due to them being hard to detect. To analyze the sentiments of tweets, a method called Linguistic Inquiry and Word Count (LIWC) was used. LIWC is a text analysis program that generates a psychologically applicable category for a word. The study findings were that most Washingtonians had neutral or negative attitude toward the belief about the possibility of preventing fatal and serious crashes. Most people had a neutral attitude about police enforcement of traffic laws that are beneficial to improving traffic safety. It was also found that most people had a neutral attitude toward six high-risk behaviors.

#### Das et al. (2020)

In another study, Das et. al sought to understand non-fear based safety campaigns public sentiments via social media. Understanding that road safety campaigns have started using social media platforms as a medium of raising awareness of road safety issues, the research objective was to use YouTube videos to understand the public perception of road safety campaigns. The authors compared two different non-fear-based advertisements and assessed the video's engagement. These two advertisements were:

1.  a series of advertisements by the Ministry of Road Transport and Highways in India

2.  "Embrace Life", a British public information film made for the Sussex Safer Roads Partnership (SSRP).

Das et. al used two tools, "tuber" and "YouTube comment scrapper" to gather associated information on these advertisements. The acquired information included the number of views, likes, dislikes, original comments, and comment replies. The research team developed two text corpora from the two campaigns. The final data sets were developed after removing the stop words, numerical values, punctuation, and other relevant words. The research team used AFINN lexicon to identify positive and negative sentiments. While the primary outcome of the study was developing a framework for similar analyses, the general findings show that comments in the Indian context are less insightful due to the presence of noise in the data set due to a high profile actor being included in the video. However, key issues such as police corruption, political influence, and nationalism were highlighted in the analysis. The UK video is mostly associated with seat belt and the praise for the ad. Increase public awareness of decreasing driver speeds in small towns and the importance of seat belt use were prevalent in the analysis. The results show that there is a different pattern of word usage when expressing emotions related to these videos.

### Research Question

My research question focuses on understanding the online discourse surrounding traffic safety in Massachusetts. My research questions are:

1.  What are the feelings of the public surrounding traffic safety in Massachusetts?

2.  What traffic safety topics do people react to the most?

3.  Does the public react overall negatively or positively about MassDOT's efforts to educate the public about safety via Twitter?

I will be analyzing tweets tagging MassDOT Twitter handles with the goal of identifying the prevailing attitude towards traffic safety and agency's approach to safety education.

After the literature review, some of my questions so far are:

1.  Will limiting the corpus to tweets tagging MassDOT introduce too much bias to the analysis?

2.  Sujon and Dai discussed there were legal contracts and payment needed to collect tweets via the Historical PowerTrack API. Will that be necessary?

### References

Sujon, M., & Dai, F. (2021). Social Media Mining for Understanding Traffic Safety Culture in Washington State Using Twitter Data. *Journal of Computing in Civil Engineering*, 35(1), 04020059. doi:10.1061/(asce)cp.1943-5487.0000943

Das, S., Dutta, A., Mudgal, A., & Datta, S. (2019). Non-fear-based Road Safety Campaign as a community service: Contexts from Social Media. *Innovations for Community Services*, 83--99. https://doi.org/10.1007/978-3-030-37484-6_5
