on:
  workflow_dispatch:
  push:
    branches: submission

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          # To install LaTeX to build PDF book 
          tinytex: true 

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.1'

      - name: Install R Dependencies
        uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::jsonlite
            any::rmarkdown
            any::tidyverse
            any::readxl
            any::summarytools
            any::psych
            any::tufte
            any::lubridate
            any::httr
            any::rtweet
            any::twitteR
            any::purrr
            any::tidytext
            any::scales
            any::broom
            any::ggplot2
            any::quanteda
            any::quanteda.textplots
            any::tm
            any::wordcloud
            any::wordcloud2
            any::reshape2
            any::gridExtra
            any::plyr
            any::pdftools
            any::cleanNLP
            any::SnowballC
            any::RColorBrewer
            any::rvest
            any::polite
            any::caret
            any::cld3
            any::corpus
            any::e1071
            any::forcats
            any::ggraph
            any::harrypotter
            any::here
            any::hunspell
            any::igraph
            any::keras
            any::LDAvis
            any::magrittr
            any::mallet
            any::Matrix
            any::NLP
            any::openNLP
            any::quanteda.textmodels
            any::quanteda.textstats
            any::randomForest
            any::reticulate
            any::readr
            any::RedditExtractoR
            any::RSelenium
            any::spacyr
            any::stm
            any::stringi
            any::stringr
            any::tensorflow
            any::text2vec
            any::textclean
            any::textshape
            any::topicmodels
            any::widyr
            any::readtext
            any::devtools
            any::DT
            any::R.utils
            any::emojifont
            any::syuzhet
            any::quarto  
            any::kableExtra
            any::servr
          cache-version: 1
          #extra-packages: any::rcmdcheck
          #needs: check
      #- uses: r-lib/actions/check-r-package@v2
      
      - name: Install Python and Dependencies
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: pip install jupyter
      - run: pip install -U -r requirements.txt

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
